CREATE TABLE "Moves" (
"Command" TEXT,
  "Character" TEXT,
  "Move category" TEXT,
  "Move Name" TEXT,
  "Stance" TEXT,
  "Hit level" TEXT,
  "Impact" REAL,
  "Damage" TEXT,
  "Block" TEXT,
  "Hit" TEXT,
  "Counter Hit" TEXT,
  "Guard Burst" TEXT,
  "Notes" TEXT,
  "ID" INTEGER,
  "DamageDec" REAL,
  "BlockDec" REAL,
  "HitDec" REAL,
  "CounterHitDeci" REAL
)